[package]
name = "triangles"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
linfa = "0.7.1"
linfa-clustering = "0.7.1"
linfa-nn = "0.7.1"
ndarray = "0.15.0"
plotters = "0.3.7"
rand = "0.8.5"
